#!/bin/bash
set -euo pipefail

# begindoc: content
heroku maintenance:on --app app-staging
prod_db=HEROKU_POSTGRESQL_BROWN_URL # follower
stag_db=HEROKU_POSTGRESQL_ROSE_URL
heroku pg:copy app-production::$prod_db $stag_db --app app-staging --confirm app-staging
heroku pg:psql --app app-staging -c "
  UPDATE ar_internal_metadata
  SET value = 'staging'
  WHERE key = 'environment';

  UPDATE users
  SET active = false
  WHERE email NOT = 'me@example.com';
"
heroku run --app app-staging rake db:migrate
heroku maintenance:off --app app-staging
# enddoc: content
