#!/bin/bash
set -euo pipefail

# begindoc: content
db="app_development"
dropdb --if-exists "$db"
createdb "$db"
psql "$db" -c "
  CREATE EXTENSION pg_stat_statements;
  CREATE SCHEMA heroku_ext;
"
pg_restore tmp/latest.backup --verbose --no-acl --no-owner --dbname "$db"
psql "$db" -c "
  UPDATE ar_internal_metadata
  SET value = 'development'
  WHERE key = 'environment'
"
# enddoc: content
