#!/bin/bash
set -euo pipefail

# begindoc: content
heroku maintenance:on --app app-staging
prod_follower_db=HEROKU_POSTGRESQL_BROWN_URL
staging_db=HEROKU_POSTGRESQL_ROSE_URL
heroku pg:copy app-production::$prod_follower_db $staging_db --app app-staging --confirm app-staging
heroku pg:psql --app app-staging -c "
  UPDATE ar_internal_metadata
  SET value = 'staging'
  WHERE key = 'environment'
"
heroku pg:psql --app app-staging -c "
  UPDATE users
  SET active = false
  WHERE email NOT = 'me@example.com'
"
heroku run --app app-staging rake db:migrate
heroku maintenance:off --app app-staging
# enddoc: content
