name: deno
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build site
        shell: bash
        run: git log -1 --format="%cd" --date="format:%a, %d %b %Y" -- articles/laptop.md
        run: go run main.go build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "croaky-blog"
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: public
