name: go
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test -v ./...

  test-macos:
    name: Test on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test -v ./...
